// Public client token snapshot. The private design source and generator are not included.
export const tokens = {
  "light": {
    "color": {
      "ink": "#20242E",
      "indigo": "#2A4A7B",
      "kapur": "#F7F2E7",
      "batu": "#DED8CB",
      "susu": "#FDFBF4",
      "rendam": "#F0EADC",
      "domainSystem": "#2E9D8F",
      "domainMoney": "#E0A32E",
      "domainBody": "#E2683F",
      "domainMind": "#8B5FA8",
      "domainSharedMoney": "#5F7A4B",
      "domainHome": "#2F6B4E",
      "domainRelationships": "#C25E85",
      "domainDocuments": "#7A6E58",
      "onDomainSystem": "#20242E",
      "onDomainMoney": "#20242E",
      "onDomainBody": "#20242E",
      "onDomainMind": "#F7F2E7",
      "onDomainSharedMoney": "#F7F2E7",
      "onDomainHome": "#F7F2E7",
      "onDomainRelationships": "#20242E",
      "onDomainDocuments": "#F7F2E7",
      "fillSystem": "#DFE8DC",
      "fillMoney": "#F4E9D1",
      "fillBody": "#F4E1D3",
      "fillMind": "#EAE0DF",
      "fillSharedMoney": "#E5E4D4",
      "fillHome": "#DFE2D5",
      "fillRelationships": "#F1E0DB",
      "fillDocuments": "#E8E2D6",
      "success": "#3A7D3F",
      "warning": "#A8701F",
      "error": "#B03535",
      "info": "#20242E",
      "surfacePage": "#F7F2E7",
      "surfaceCard": "#FDFBF4",
      "surfaceInset": "#F0EADC",
      "textPrimary": "#20242E",
      "textSecondary": "rgba(32,36,46,.62)",
      "textOnInteractive": "#F7F2E7",
      "borderStructure": "#DED8CB",
      "borderEmphasis": "#20242E",
      "interactive": "#2A4A7B",
      "interactivePressed": "#1F3A63",
      "focusRing": "#2A4A7B",
      "disabledFg": "rgba(32,36,46,.38)",
      "disabledBg": "#DED8CB",
      "stateDeparted": "grayscale(1)",
    },
    "typography": {
      "fontDisplay": "Pixelify Sans",
      "fontText": "Plus Jakarta Sans",
      "textH1": {
        "fontWeight": 400,
        "fontSize": 40,
        "lineHeight": 44,
        "fontFamily": "Pixelify Sans",
      },
      "trackingH1": -0.5,
      "textH2": {
        "fontWeight": 400,
        "fontSize": 30,
        "lineHeight": 36,
        "fontFamily": "Pixelify Sans",
      },
      "textH3": {
        "fontWeight": 500,
        "fontSize": 22,
        "lineHeight": 30,
        "fontFamily": "Plus Jakarta Sans",
      },
      "textH4": {
        "fontWeight": 500,
        "fontSize": 17,
        "lineHeight": 26,
        "fontFamily": "Plus Jakarta Sans",
      },
      "textKeyword": {
        "fontWeight": 700,
        "fontSize": 20,
        "lineHeight": 24,
        "fontFamily": "Pixelify Sans",
      },
      "textBody": {
        "fontWeight": 400,
        "fontSize": 16,
        "lineHeight": 26,
        "fontFamily": "Plus Jakarta Sans",
      },
      "textSmall": {
        "fontWeight": 400,
        "fontSize": 13,
        "lineHeight": 20,
        "fontFamily": "Plus Jakarta Sans",
      },
      "textLabel": {
        "fontWeight": 500,
        "fontSize": 11,
        "lineHeight": 16,
        "fontFamily": "Plus Jakarta Sans",
      },
      "trackingLabel": "0.08em",
    },
    "spacing": {
      "space-1": 8,
      "space-2": 16,
      "space-3": 24,
      "space-4": 32,
      "space-5": 40,
      "space-6": 48,
      "space-7": 56,
      "space-8": 64,
      "radiusContent": 0,
      "radiusControl": 4,
      "borderW": 1,
      "borderWEmphasis": 2,
      "controlH": 48,
      "controlHSm": 40,
      "controlHLg": 56,
    },
    "motion": {
      "durationFast": 120,
      "durationStandard": 160,
      "durationMax": 240,
      "easeOut": "cubic-bezier(0,0,.2,1)",
      "reduced": {
        "durationFast": 0,
        "durationStandard": 0,
        "durationMax": 0,
      },
    },
  },
  "dark": {
    "color": {
      "ink": "#20242E",
      "indigo": "#2A4A7B",
      "kapur": "#F7F2E7",
      "batu": "#DED8CB",
      "susu": "#FDFBF4",
      "rendam": "#F0EADC",
      "domainSystem": "#2E9D8F",
      "domainMoney": "#E0A32E",
      "domainBody": "#E2683F",
      "domainMind": "#8B5FA8",
      "domainSharedMoney": "#5F7A4B",
      "domainHome": "#46966F",
      "domainRelationships": "#C25E85",
      "domainDocuments": "#7A6E58",
      "onDomainSystem": "#20242E",
      "onDomainMoney": "#20242E",
      "onDomainBody": "#20242E",
      "onDomainMind": "#F7F2E7",
      "onDomainSharedMoney": "#F7F2E7",
      "onDomainHome": "#F7F2E7",
      "onDomainRelationships": "#20242E",
      "onDomainDocuments": "#F7F2E7",
      "fillSystem": "#22333A",
      "fillMoney": "#37332E",
      "fillBody": "#372C30",
      "fillMind": "#2D2B3D",
      "fillSharedMoney": "#282E31",
      "fillHome": "#253236",
      "fillRelationships": "#332B38",
      "fillDocuments": "#2B2D33",
      "success": "#7CBF80",
      "warning": "#E0A94E",
      "error": "#E08A7E",
      "info": "#F7F2E7",
      "surfacePage": "#20242E",
      "surfaceCard": "#272C38",
      "surfaceInset": "#2D3341",
      "textPrimary": "#F7F2E7",
      "textSecondary": "rgba(247,242,231,.62)",
      "textOnInteractive": "#20242E",
      "borderStructure": "#3A4150",
      "borderEmphasis": "#F7F2E7",
      "interactive": "#8FADD6",
      "interactivePressed": "#A9C1E2",
      "focusRing": "#8FADD6",
      "disabledFg": "rgba(247,242,231,.38)",
      "disabledBg": "#3A4150",
      "stateDeparted": "grayscale(1)",
      "gridTexture": "#2E3542",
    },
    "typography": {
      "fontDisplay": "Pixelify Sans",
      "fontText": "Plus Jakarta Sans",
      "textH1": {
        "fontWeight": 400,
        "fontSize": 40,
        "lineHeight": 44,
        "fontFamily": "Pixelify Sans",
      },
      "trackingH1": -0.5,
      "textH2": {
        "fontWeight": 400,
        "fontSize": 30,
        "lineHeight": 36,
        "fontFamily": "Pixelify Sans",
      },
      "textH3": {
        "fontWeight": 500,
        "fontSize": 22,
        "lineHeight": 30,
        "fontFamily": "Plus Jakarta Sans",
      },
      "textH4": {
        "fontWeight": 500,
        "fontSize": 17,
        "lineHeight": 26,
        "fontFamily": "Plus Jakarta Sans",
      },
      "textKeyword": {
        "fontWeight": 700,
        "fontSize": 20,
        "lineHeight": 24,
        "fontFamily": "Pixelify Sans",
      },
      "textBody": {
        "fontWeight": 400,
        "fontSize": 16,
        "lineHeight": 26,
        "fontFamily": "Plus Jakarta Sans",
      },
      "textSmall": {
        "fontWeight": 400,
        "fontSize": 13,
        "lineHeight": 20,
        "fontFamily": "Plus Jakarta Sans",
      },
      "textLabel": {
        "fontWeight": 500,
        "fontSize": 11,
        "lineHeight": 16,
        "fontFamily": "Plus Jakarta Sans",
      },
      "trackingLabel": "0.08em",
    },
    "spacing": {
      "space-1": 8,
      "space-2": 16,
      "space-3": 24,
      "space-4": 32,
      "space-5": 40,
      "space-6": 48,
      "space-7": 56,
      "space-8": 64,
      "radiusContent": 0,
      "radiusControl": 4,
      "borderW": 1,
      "borderWEmphasis": 2,
      "controlH": 48,
      "controlHSm": 40,
      "controlHLg": 56,
    },
    "motion": {
      "durationFast": 120,
      "durationStandard": 160,
      "durationMax": 240,
      "easeOut": "cubic-bezier(0,0,.2,1)",
      "reduced": {
        "durationFast": 0,
        "durationStandard": 0,
        "durationMax": 0,
      },
    },
  },
} as const;

export type Tokens = typeof tokens;
